### ISSUE TITLE
[Feature request] Declare var scoreboard type as trigger

### ISSUE THREAD

**Issue by Shamus03** [Stevertus/mcscript#20]
Variables are always declared as type "dummy".  To allow the `/trigger` command they must be declared as type "trigger"

Currently, declaring a var yields this:
```
var myVariable
==> /scoreboard objectives add myVariable dummy
```

I would like to be able to declare a trigger somehow.  Either with a new keyword similar to "var" or an argument after the variable name:

```
var myVariable trigger
==> /scoreboard objectives add myVariable trigger
```

**Comment by Stevertus** [comment]
I can see a usecase there, but I am not adding new features to mcscript anymore, because the work required to rearrange everything is too much.

**Comment by Stevertus** [comment]
added in v0.2.3
