### ISSUE TITLE
compiler inserts semicolons before newlines when using .repl()

### ISSUE THREAD

**Issue by deli73** [Stevertus/mcscript#21]
when given this text in a .mcscript file:
```
const TEST_CONST = 'this is a demonstration
of the issue with constants in MCScript'
/say $(TEST_CONST).repl(" the ", " an ")
```

the following is output in the mcfunction by the compiler:
```
say this is a demonstration;
of an issue with constants in MCScript
```

note the erroneous semicolon. it appears that the replace feature was created without multi-line constants in mind, but those are really useful for certain things so it'd be cool if this was fixed. thanks!

**Comment by deli73** [comment]
also this may warrant another issue but: a much stranger issue occurs when you have more than one .repl() in a single mcscript file:
```
TypeError: Cannot read property '0' of undefined
    at con.forEach ([...]\node_modules\mcscript\lib\generator.js:92:30)
```

**Comment by Stevertus** [comment]
This might be pretty long ago, but for me the provided example works fine. You may want to update to the newest version.
I can also see no issues with multiple repls. If you still encounter this issue, dont bother writing another message.
