### ISSUE TITLE
Support for cross-dimensions

### ISSUE THREAD

**Issue by RetroMiner19** [Stevertus/mcscript#27]
Hi. First off, i'm loving using mcscript! I am making a continuous game, which is spread out between multiple dimensions. Your compiler doesn't seem to like:
```
in('minecraft:minigames'){
run: say hi
}
```
so therefore I am having to work around it by doing:
```
as('@s in minecraft:minigames'){
run: say hi
}
```
The workaround isn't that annoying, it's not a big deal. My issue is, I am now having to use that extra ```as @s``` where it is not needed. 

Once again, thanks for providing such an amazing resource. It takes a lot of the repeating out and is generally really clean and easy to use.
Retro

**Comment by Stevertus** [comment]
Thank you for this report. Mcscript has the dimension keyword for this, so you can literally use
```
dimension('minecraft:minigames'){
run: say hi
}
```
Nevertheless I´ve also included in as an alias for it in the upcoming version
