### ISSUE TITLE
All files generate with 2 whitespace characters on the end

### ISSUE THREAD

**Issue by ChildishGiant** [Stevertus/mcscript#29]
![image](https://user-images.githubusercontent.com/13716824/93693537-f788ea00-faf8-11ea-837f-55b455950761.png)
![image](https://user-images.githubusercontent.com/13716824/93693538-fd7ecb00-faf8-11ea-9de2-18b679c9c7ad.png)
![image](https://user-images.githubusercontent.com/13716824/93693539-0079bb80-faf9-11ea-8d99-a3804711f4d5.png)
![image](https://user-images.githubusercontent.com/13716824/93693541-0cfe1400-faf9-11ea-9747-5548ca1f2b2f.png)
![image](https://user-images.githubusercontent.com/13716824/93693544-125b5e80-faf9-11ea-9005-f0486cc52746.png)

You get the idea

**Comment by Stevertus** [comment]
fixed in v0.2.3
