### ISSUE TITLE
MCscript is dangerous?!

### ISSUE THREAD

**Issue by Libertas007** [Stevertus/mcscript#31]
Hi everyone!
When I run `mcscript new` and name of my project, I have a lot of errors and my antivirus (Avast) is blocking your files (.html files in node package). And my browser is telling me, that some parts of your website (dManager and mcscript) are dangerous (mcscript website is blocked by Avast too).
Is it really dangerous or it should be an error in my antivirus?
Thanks!

EDIT: When I deleted docs folder, everything worked fine.

**Comment by Heath123** [comment]
It's probably just your antivirus not trusting thst it's making a bunch of files (maybe viruses do that to copy themselves)? It's fine, HTML files can't (easily) be dangerous and the code is public so someone would have seen.

**Comment by Stevertus** [comment]
My only guess would also be writing a lot of files to a folder caused this. And the docs folders should usually not be in the npm release, maybe I messed up something.

For the dManager page, yes that is indeed insecure. I will have to renew the certificate, thanks.
